#!/usr/bin/env bash
# 2x number of webservers
sudo apt-get -y update && sudo apt-get -y install haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy
sudo sed -i "\$ a\listen 289739-lb-01\n\tbind *:80\n\tmode http\n\tstats enable\n\tbalance roundrobin\n\tserver 289739-web-01 18.233.67.229:80 check\n\tserver 289739-web-02 100.25.22.49:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
